---
title: "Weather Data Project"
author: "Rebecca Sullivan"
date: "5/6/2022"
output: 
  html_document:
    theme: spacelab
    toc: true
    toc_float: true
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = FALSE}
if(! require("pacman")) install.packages("pacman")

pacman::p_load(
  tidyverse,
  here,
  lubridate
)

source(here::here ("Scripts", "functions.R") )

```

# About

# Data

### Csv files were requested from the National Oceanic and Atmospheric Administration data page: https://www.ncdc.noaa.gov/cdo-web/

```{r,  include = FALSE}
weather_1 <- read_csv(here::here("Data", "2938751.csv")) %>% 
  select (STATION, NAME, LATITUDE, LONGITUDE,  ELEVATION, DATE, PRCP, SNOW, TMAX, TMIN  )

weather_3 <- read_csv(here::here("Data", "2966466.csv")) %>% 
  select (STATION, NAME, LATITUDE, LONGITUDE,  ELEVATION, DATE, PRCP, SNOW, TMAX, TMIN  )


weather <- union (weather_1, weather_3) %>% 
  mutate (Location = NAME ,
          Year = year(DATE),
          Month = months(DATE),
          Quarter = quarters(DATE), 
          Daily_Temp_Change = TMAX - TMIN)  %>% 
  filter(Year %in% c(2019, 2020, 2021))


```



```{r}
weather %>% 
  count(STATION, Location)

weather %>% 
  count(Location, Year) 

```

## Temperature Variation

```{r}
weather %>% 
  filter( STATION != 'USC00053446' ) %>% 
  ggplot(aes ( y = TMAX ,
               group = Location, 
               color = Location)) +
  geom_boxplot(na.rm = T )    +
  labs(
        y = "Maximum Daily Temperature in Degrees F" ,
    title = "Daily Temperature Variation 2019 - 2021" ,
    subtitle = "by Weather Station",
    caption = "Data from www.noaa.gov") +
    theme_gray()  +
    theme(axis.title = element_text(face = "bold"),
        axis.text = element_text(face = "italic") ,
         axis.text.x = element_blank( ) )

```

```{r}
weather %>% 
  filter( STATION != 'USC00053446' ) %>% 
  ggplot(aes ( y = TMIN,
               group = Location, 
               color = Location)) +
  geom_boxplot(na.rm = T ) +
      labs(
        y = "Minimum Daily Temperature in Degrees F" ,
    title = "Daily Temperature Variation 2019 - 2021" ,
    subtitle = "by Weather Station",
    caption = "Data from www.noaa.gov") +
    theme_gray()  +
    theme(axis.title = element_text(face = "bold"),
        axis.text = element_text(face = "italic") ,
        axis.text.x = element_blank( ) )

```



# Varation over Time




## Daily Differences
```{r}

weather %>% 
graph_temps(Station_code ="USW00013739")


weather %>% 
graph_temps(Station_code ="USC00396427")

weather %>% 
graph_temps(Station_code ="USW00013967")


weather %>% 
graph_temps(Station_code ="USW00093812")
```




```{r}
weather %>% 
  filter( STATION != 'USC00053446' ) %>% 
  ggplot(aes ( y = Daily_Temp_Change,
               group = Location, 
               color = Location)) +
  geom_boxplot(na.rm = T ) +
  labs(
        y = "Daily Temperature Change in Degrees F" ,
    title = "Temperature Variation 2019 - 2021" ,
    subtitle = "by Weather Station",
    caption = "Data from www.noaa.gov") +
    theme_gray()  +
    theme(axis.title = element_text(face = "bold"),
        axis.text = element_text(face = "italic") ,
        axis.text.x = element_blank( ) )
```
```{r}


weather <-
  weather %>% 
  filter( Year %in% c(2019, 2020, 2021)) %>% 
  mutate( cold_flag = if_else(condition = TMIN <= 32, 
                                  true = T, 
                                  false = F, 
                              missing = NA)   ) %>%
    mutate( hot_flag = if_else(condition = TMAX >= 90, 
                                  true = T, 
                                  false = F, 
                              missing = NA) ) 

  weather %>% 
  count(cold_flag, hot_flag) 
```
```{r}

```

